name: clarityhub
description: Record and add photos for your customer interviews.

version: 1.1.0+2
 
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_vector_icons: ^0.2.1
  shared_preferences: 0.5.3+4
  flutter_launcher_icons: ^0.7.3
  http: ^0.12.0+2
  modal_progress_hud: ^0.1.3
  flutter_auth0: ^0.5.0
  fluttertoast: 4.0.1
  flutter_config: 1.0.5
  pull_to_refresh: ^1.5.7
  redux: 4.0.0
  redux_thunk: 0.3.0
  flutter_redux: 0.6.0
  redux_logging: 0.4.0
  url_launcher: 5.4.5
  flutter_linkify: 3.1.0
  google_fonts: 0.6.2
  intl: 0.16.1
  audioplayers: ^0.15.1
  camera: 0.5.7+4
  flutter_speed_dial: 1.2.5
  flutter_sound_lite: 5.1.1
  flutter_local_notifications: 1.4.2
  flutter_uploader: 1.2.0
  image_picker: 0.6.5+2
  redux_persist: 0.8.4
  redux_persist_flutter: 0.8.2
  intro_slider: 2.2.9
  permission_handler: 5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logocircle.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

